name: flutter_blue_ultra_accessory_setup
description: >-
  Use it to discover and configure Bluetooth or Wi-Fi accessories with images and names provided by the app.
  Works on iOS 18 and above, and bridges AccessorySetupKit through platform channels.
version: 0.1.0
homepage: https://github.com/dotintent/flutter_blue_ultra/tree/main/packages/flutter_blue_ultra_accessory_setup
repository: https://github.com/dotintent/flutter_blue_ultra
issue_tracker: https://github.com/dotintent/flutter_blue_ultra/issues
topics:
  - ios
  - bluetooth
  - ble
  - accessorysetupkit

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  pigeon: ^27.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAccessorySetupPlugin
