// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `ASAccessoryEventType`. Raw values are not exposed to Dart; the
/// native side maps the platform enum onto these cases.
enum AccessoryEventType: Int, CaseIterable {
  case unknown = 0
  case activated = 1
  case invalidated = 2
  case migrationComplete = 3
  case accessoryAdded = 4
  case accessoryRemoved = 5
  case accessoryChanged = 6
  case accessoryDiscovered = 7
  case pickerDidPresent = 8
  case pickerDidDismiss = 9
  case pickerSetupBridging = 10
  case pickerSetupFailed = 11
  case pickerSetupPairing = 12
  case pickerSetupRename = 13
}

/// Mirrors `ASAccessoryState`.
enum AccessoryState: Int, CaseIterable {
  case unauthorized = 0
  case awaitingAuthorization = 1
  case authorized = 2
}

/// A serializable view of `NSError` raised by the native layer.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeError: Hashable, CustomStringConvertible {
  var domain: String
  var code: Int64
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeError? {
    let domain = pigeonVar_list[0] as! String
    let code = pigeonVar_list[1] as! Int64
    let message = pigeonVar_list[2] as! String

    return NativeError(
      domain: domain,
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      domain,
      code,
      message,
    ]
  }
  static func == (lhs: NativeError, rhs: NativeError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.domain, rhs.domain) && MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeError")
    MessagesPigeonInternal.deepHash(value: domain, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "NativeError(domain: \(String(describing: domain)), code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

/// A serializable view of `ASAccessory`. The real native object is retained on
/// the host side, keyed by [bluetoothIdentifier].
///
/// Generated class from Pigeon that represents data sent in messages.
struct Accessory: Hashable, CustomStringConvertible {
  var bluetoothIdentifier: String? = nil
  var displayName: String
  var state: AccessoryState
  var ssid: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Accessory? {
    let bluetoothIdentifier: String? = nilOrValue(pigeonVar_list[0])
    let displayName = pigeonVar_list[1] as! String
    let state = pigeonVar_list[2] as! AccessoryState
    let ssid: String? = nilOrValue(pigeonVar_list[3])

    return Accessory(
      bluetoothIdentifier: bluetoothIdentifier,
      displayName: displayName,
      state: state,
      ssid: ssid
    )
  }
  func toList() -> [Any?] {
    return [
      bluetoothIdentifier,
      displayName,
      state,
      ssid,
    ]
  }
  static func == (lhs: Accessory, rhs: Accessory) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.bluetoothIdentifier, rhs.bluetoothIdentifier) && MessagesPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.ssid, rhs.ssid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Accessory")
    MessagesPigeonInternal.deepHash(value: bluetoothIdentifier, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ssid, hasher: &hasher)
  }

  public var description: String {
    return "Accessory(bluetoothIdentifier: \(String(describing: bluetoothIdentifier)), displayName: \(String(describing: displayName)), state: \(String(describing: state)), ssid: \(String(describing: ssid)))"
  }
}

/// A session event delivered from the native layer to Dart.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccessoryEvent: Hashable, CustomStringConvertible {
  var type: AccessoryEventType
  var accessory: Accessory? = nil
  var error: NativeError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AccessoryEvent? {
    let type = pigeonVar_list[0] as! AccessoryEventType
    let accessory: Accessory? = nilOrValue(pigeonVar_list[1])
    let error: NativeError? = nilOrValue(pigeonVar_list[2])

    return AccessoryEvent(
      type: type,
      accessory: accessory,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      accessory,
      error,
    ]
  }
  static func == (lhs: AccessoryEvent, rhs: AccessoryEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.accessory, rhs.accessory) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AccessoryEvent")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: accessory, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "AccessoryEvent(type: \(String(describing: type)), accessory: \(String(describing: accessory)), error: \(String(describing: error)))"
  }
}

/// Configuration for a single entry shown in the picker.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PickerDisplayItem: Hashable, CustomStringConvertible {
  var name: String
  var imageBytes: FlutterStandardTypedData
  var serviceUuid: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickerDisplayItem? {
    let name = pigeonVar_list[0] as! String
    let imageBytes = pigeonVar_list[1] as! FlutterStandardTypedData
    let serviceUuid: String? = nilOrValue(pigeonVar_list[2])

    return PickerDisplayItem(
      name: name,
      imageBytes: imageBytes,
      serviceUuid: serviceUuid
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      imageBytes,
      serviceUuid,
    ]
  }
  static func == (lhs: PickerDisplayItem, rhs: PickerDisplayItem) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.imageBytes, rhs.imageBytes) && MessagesPigeonInternal.deepEquals(lhs.serviceUuid, rhs.serviceUuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PickerDisplayItem")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: serviceUuid, hasher: &hasher)
  }

  public var description: String {
    return "PickerDisplayItem(name: \(String(describing: name)), imageBytes: \(String(describing: imageBytes)), serviceUuid: \(String(describing: serviceUuid)))"
  }
}

/// Mirrors `ASAccessory.RenameOptions`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RenameOptions: Hashable, CustomStringConvertible {
  var renameSSID: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RenameOptions? {
    let renameSSID = pigeonVar_list[0] as! Bool

    return RenameOptions(
      renameSSID: renameSSID
    )
  }
  func toList() -> [Any?] {
    return [
      renameSSID
    ]
  }
  static func == (lhs: RenameOptions, rhs: RenameOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.renameSSID, rhs.renameSSID)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RenameOptions")
    MessagesPigeonInternal.deepHash(value: renameSSID, hasher: &hasher)
  }

  public var description: String {
    return "RenameOptions(renameSSID: \(String(describing: renameSSID)))"
  }
}

/// Mirrors the mutable fields of `ASAccessorySettings`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccessorySettings: Hashable, CustomStringConvertible {
  var ssid: String? = nil
  var bluetoothTransportBridgingIdentifier: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AccessorySettings? {
    let ssid: String? = nilOrValue(pigeonVar_list[0])
    let bluetoothTransportBridgingIdentifier: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return AccessorySettings(
      ssid: ssid,
      bluetoothTransportBridgingIdentifier: bluetoothTransportBridgingIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      ssid,
      bluetoothTransportBridgingIdentifier,
    ]
  }
  static func == (lhs: AccessorySettings, rhs: AccessorySettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.ssid, rhs.ssid) && MessagesPigeonInternal.deepEquals(lhs.bluetoothTransportBridgingIdentifier, rhs.bluetoothTransportBridgingIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AccessorySettings")
    MessagesPigeonInternal.deepHash(value: ssid, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bluetoothTransportBridgingIdentifier, hasher: &hasher)
  }

  public var description: String {
    return "AccessorySettings(ssid: \(String(describing: ssid)), bluetoothTransportBridgingIdentifier: \(String(describing: bluetoothTransportBridgingIdentifier)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AccessoryEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AccessoryState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return NativeError.fromList(self.readValue() as! [Any?])
    case 132:
      return Accessory.fromList(self.readValue() as! [Any?])
    case 133:
      return AccessoryEvent.fromList(self.readValue() as! [Any?])
    case 134:
      return PickerDisplayItem.fromList(self.readValue() as! [Any?])
    case 135:
      return RenameOptions.fromList(self.readValue() as! [Any?])
    case 136:
      return AccessorySettings.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AccessoryEventType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AccessoryState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeError {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Accessory {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AccessoryEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PickerDisplayItem {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RenameOptions {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AccessorySettings {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native calls. Methods that wrap an AccessorySetupKit completion
/// handler are `@async`; their futures complete (or throw a [PlatformException])
/// when the native callback fires.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AccessorySetupApi {
  /// Activates the session. Returns immediately; the
  /// [AccessoryEventType.activated] event signals completion.
  func activate() throws
  func showPicker(completion: @escaping (Result<Void, Error>) -> Void)
  func showPickerForItems(items: [PickerDisplayItem], completion: @escaping (Result<Void, Error>) -> Void)
  func showPickerForDevice(name: String, imageBytes: FlutterStandardTypedData, serviceUuid: String, completion: @escaping (Result<Void, Error>) -> Void)
  func removeAccessory(accessoryId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func renameAccessory(accessoryId: String, options: RenameOptions, completion: @escaping (Result<Void, Error>) -> Void)
  func finishAuthorization(accessoryId: String, settings: AccessorySettings, completion: @escaping (Result<Void, Error>) -> Void)
  func failAuthorization(accessoryId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getAccessories() throws -> [Accessory]
  func getLogs() throws -> [String]
  func invalidate() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AccessorySetupApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AccessorySetupApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AccessorySetupApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Activates the session. Returns immediately; the
    /// [AccessoryEventType.activated] event signals completion.
    let activateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.activate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activateChannel.setMessageHandler { _, reply in
        do {
          try api.activate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      activateChannel.setMessageHandler(nil)
    }
    let showPickerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPicker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPickerChannel.setMessageHandler { _, reply in
        api.showPicker { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showPickerChannel.setMessageHandler(nil)
    }
    let showPickerForItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPickerForItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPickerForItemsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemsArg = args[0] as! [PickerDisplayItem]
        api.showPickerForItems(items: itemsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showPickerForItemsChannel.setMessageHandler(nil)
    }
    let showPickerForDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPickerForDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPickerForDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let imageBytesArg = args[1] as! FlutterStandardTypedData
        let serviceUuidArg = args[2] as! String
        api.showPickerForDevice(name: nameArg, imageBytes: imageBytesArg, serviceUuid: serviceUuidArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showPickerForDeviceChannel.setMessageHandler(nil)
    }
    let removeAccessoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.removeAccessory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAccessoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessoryIdArg = args[0] as! String
        api.removeAccessory(accessoryId: accessoryIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAccessoryChannel.setMessageHandler(nil)
    }
    let renameAccessoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.renameAccessory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renameAccessoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessoryIdArg = args[0] as! String
        let optionsArg = args[1] as! RenameOptions
        api.renameAccessory(accessoryId: accessoryIdArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      renameAccessoryChannel.setMessageHandler(nil)
    }
    let finishAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.finishAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessoryIdArg = args[0] as! String
        let settingsArg = args[1] as! AccessorySettings
        api.finishAuthorization(accessoryId: accessoryIdArg, settings: settingsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      finishAuthorizationChannel.setMessageHandler(nil)
    }
    let failAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.failAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      failAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessoryIdArg = args[0] as! String
        api.failAuthorization(accessoryId: accessoryIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      failAuthorizationChannel.setMessageHandler(nil)
    }
    let getAccessoriesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.getAccessories\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccessoriesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAccessories()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAccessoriesChannel.setMessageHandler(nil)
    }
    let getLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.getLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLogsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLogs()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLogsChannel.setMessageHandler(nil)
    }
    let invalidateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.invalidate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateChannel.setMessageHandler { _, reply in
        do {
          try api.invalidate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      invalidateChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart calls.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AccessorySetupFlutterApiProtocol {
  func onAccessoryEvent(event eventArg: AccessoryEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AccessorySetupFlutterApi: AccessorySetupFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onAccessoryEvent(event eventArg: AccessoryEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupFlutterApi.onAccessoryEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
