// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors `ASAccessoryEventType`. Raw values are not exposed to Dart; the
/// native side maps the platform enum onto these cases.
enum AccessoryEventType {
  unknown,
  activated,
  invalidated,
  migrationComplete,
  accessoryAdded,
  accessoryRemoved,
  accessoryChanged,
  accessoryDiscovered,
  pickerDidPresent,
  pickerDidDismiss,
  pickerSetupBridging,
  pickerSetupFailed,
  pickerSetupPairing,
  pickerSetupRename,
}

/// Mirrors `ASAccessoryState`.
enum AccessoryState {
  unauthorized,
  awaitingAuthorization,
  authorized,
}

/// A serializable view of `NSError` raised by the native layer.
class NativeError {
  NativeError({
    required this.domain,
    required this.code,
    required this.message,
  });

  String domain;

  int code;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      domain,
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeError decode(Object result) {
    result as List<Object?>;
    return NativeError(
      domain: result[0]! as String,
      code: result[1]! as int,
      message: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(domain, other.domain) &&
        _deepEquals(code, other.code) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeError(domain: $domain, code: $code, message: $message)';
  }
}

/// A serializable view of `ASAccessory`. The real native object is retained on
/// the host side, keyed by [bluetoothIdentifier].
class Accessory {
  Accessory({
    this.bluetoothIdentifier,
    required this.displayName,
    required this.state,
    this.ssid,
  });

  String? bluetoothIdentifier;

  String displayName;

  AccessoryState state;

  String? ssid;

  List<Object?> _toList() {
    return <Object?>[
      bluetoothIdentifier,
      displayName,
      state,
      ssid,
    ];
  }

  Object encode() {
    return _toList();
  }

  static Accessory decode(Object result) {
    result as List<Object?>;
    return Accessory(
      bluetoothIdentifier: result[0] as String?,
      displayName: result[1]! as String,
      state: result[2]! as AccessoryState,
      ssid: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Accessory || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bluetoothIdentifier, other.bluetoothIdentifier) &&
        _deepEquals(displayName, other.displayName) &&
        _deepEquals(state, other.state) &&
        _deepEquals(ssid, other.ssid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'Accessory(bluetoothIdentifier: $bluetoothIdentifier, displayName: $displayName, state: $state, ssid: $ssid)';
  }
}

/// A session event delivered from the native layer to Dart.
class AccessoryEvent {
  AccessoryEvent({
    required this.type,
    this.accessory,
    this.error,
  });

  AccessoryEventType type;

  Accessory? accessory;

  NativeError? error;

  List<Object?> _toList() {
    return <Object?>[
      type,
      accessory,
      error,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AccessoryEvent decode(Object result) {
    result as List<Object?>;
    return AccessoryEvent(
      type: result[0]! as AccessoryEventType,
      accessory: result[1] as Accessory?,
      error: result[2] as NativeError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AccessoryEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(accessory, other.accessory) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AccessoryEvent(type: $type, accessory: $accessory, error: $error)';
  }
}

/// Configuration for a single entry shown in the picker.
class PickerDisplayItem {
  PickerDisplayItem({
    required this.name,
    required this.imageBytes,
    this.serviceUuid,
  });

  String name;

  Uint8List imageBytes;

  String? serviceUuid;

  List<Object?> _toList() {
    return <Object?>[
      name,
      imageBytes,
      serviceUuid,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PickerDisplayItem decode(Object result) {
    result as List<Object?>;
    return PickerDisplayItem(
      name: result[0]! as String,
      imageBytes: result[1]! as Uint8List,
      serviceUuid: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickerDisplayItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(imageBytes, other.imageBytes) &&
        _deepEquals(serviceUuid, other.serviceUuid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PickerDisplayItem(name: $name, imageBytes: $imageBytes, serviceUuid: $serviceUuid)';
  }
}

/// Mirrors `ASAccessory.RenameOptions`.
class RenameOptions {
  RenameOptions({
    this.renameSSID = false,
  });

  bool renameSSID;

  List<Object?> _toList() {
    return <Object?>[
      renameSSID,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RenameOptions decode(Object result) {
    result as List<Object?>;
    return RenameOptions(
      renameSSID: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RenameOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(renameSSID, other.renameSSID);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RenameOptions(renameSSID: $renameSSID)';
  }
}

/// Mirrors the mutable fields of `ASAccessorySettings`.
class AccessorySettings {
  AccessorySettings({
    this.ssid,
    this.bluetoothTransportBridgingIdentifier,
  });

  String? ssid;

  Uint8List? bluetoothTransportBridgingIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      ssid,
      bluetoothTransportBridgingIdentifier,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AccessorySettings decode(Object result) {
    result as List<Object?>;
    return AccessorySettings(
      ssid: result[0] as String?,
      bluetoothTransportBridgingIdentifier: result[1] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AccessorySettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ssid, other.ssid) &&
        _deepEquals(bluetoothTransportBridgingIdentifier,
            other.bluetoothTransportBridgingIdentifier);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AccessorySettings(ssid: $ssid, bluetoothTransportBridgingIdentifier: $bluetoothTransportBridgingIdentifier)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AccessoryEventType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AccessoryState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativeError) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is Accessory) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is AccessoryEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PickerDisplayItem) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RenameOptions) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is AccessorySettings) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AccessoryEventType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AccessoryState.values[value];
      case 131:
        return NativeError.decode(readValue(buffer)!);
      case 132:
        return Accessory.decode(readValue(buffer)!);
      case 133:
        return AccessoryEvent.decode(readValue(buffer)!);
      case 134:
        return PickerDisplayItem.decode(readValue(buffer)!);
      case 135:
        return RenameOptions.decode(readValue(buffer)!);
      case 136:
        return AccessorySettings.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> native calls. Methods that wrap an AccessorySetupKit completion
/// handler are `@async`; their futures complete (or throw a [PlatformException])
/// when the native callback fires.
class AccessorySetupApi {
  /// Constructor for [AccessorySetupApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AccessorySetupApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Activates the session. Returns immediately; the
  /// [AccessoryEventType.activated] event signals completion.
  Future<void> activate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.activate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showPicker() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPicker$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showPickerForItems(List<PickerDisplayItem> items) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPickerForItems$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[items]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showPickerForDevice(
      String name, Uint8List imageBytes, String serviceUuid) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.showPickerForDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[name, imageBytes, serviceUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> removeAccessory(String accessoryId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.removeAccessory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[accessoryId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> renameAccessory(
      String accessoryId, RenameOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.renameAccessory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[accessoryId, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> finishAuthorization(
      String accessoryId, AccessorySettings settings) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.finishAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[accessoryId, settings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> failAuthorization(String accessoryId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.failAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[accessoryId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<Accessory>> getAccessories() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.getAccessories$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<Accessory>();
  }

  Future<List<String>> getLogs() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.getLogs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<void> invalidate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupApi.invalidate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Native -> Dart calls.
abstract class AccessorySetupFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAccessoryEvent(AccessoryEvent event);

  static void setUp(
    AccessorySetupFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_blue_ultra_accessory_setup.AccessorySetupFlutterApi.onAccessoryEvent$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AccessoryEvent arg_event = args[0]! as AccessoryEvent;
          try {
            api.onAccessoryEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
