include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Allow print statements for debugging
    avoid_print: false

    # Additional rules for plugin packages
    public_member_api_docs: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_returning_null_for_void: true
    avoid_void_async: true
    unawaited_futures: true
    use_super_parameters: true
    unnecessary_lambdas: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    argument_type_not_assignable: ignore